### ISSUE TITLE
Error checking for updates

### ISSUE THREAD

**Issue by manzomium** [adieyal/sd-dynamic-prompts#159] opened 2023-01-07 12:56 UTC
**Describe the bug**
While chekcking for updates, I get an error message. it happened while on 2.0.03 or 1.5.17

**Expected behaviour**
I expect the update to be found and installed correctly

**Additional context**
here's what the console says

Error checking updates for dynamic-prompts:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 61, in check_updates
    ext.check_updates()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 61, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "/usr/local/lib/python3.8/dist-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.8/dist-packages/git/remote.py", line 763, in _get_fetch_info_from_stderr
    with open(fetch_head.abspath, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/dynamic-prompts/.git/FETCH_HEAD'

**Comment by adieyal** [comment] 2023-01-07 16:19
which colab are you using?

**Comment by manzomium** [comment] 2023-01-07 16:22
Automatic 1111, the last Ben version

**Comment by manzomium** [comment] 2023-01-07 17:56
I've removed everything from the extension file, installed it via git (although [I'm not seeing the wildcard folder](https://github.com/adieyal/sd-dynamic-prompts/issues/161#issue-1524019856))

Here's the error message I get now:

Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/dynamic-prompts/scripts/dynamic_prompting.py", line 15, in <module>
    from dynamicprompts.wildcardmanager import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts'

Thank you for your help, and sorry to bother you - it's just because your extension make the creative experience much more creative/fun

**Comment by adieyal** [comment] 2023-01-07 20:49
Closing this as the issue is being discussed here: https://github.com/adieyal/sd-dynamic-prompts/issues/161

**Closed by adieyal** 2023-01-07 20:49 UTC
