### ISSUE TITLE
Additional whitespace pre and post pended to wildcard results

### ISSUE THREAD

**Issue by nordylocks** [adieyal/sd-dynamic-prompts#153] opened 2023-01-05 18:16 UTC
**Describe the bug**
An additional whitespace (space) is prepended and postpended to the results of the wildcard replacement.

**To Reproduce**
`Create a simple prompt "a blue sky:__weight__  over a hill"`
weight.txt exists with values from 0.0 to 1.0
prompt created will be "a blue sky: 0.4 over a hill"

Only the dynamic prompt is enabled.

**Expected behaviour**
Expect the prompt to respect the formating pre-parsing. IE: "a blue sky:0.4 over a hill"

**Additional context**
only seems to pre and post pend if a whitespace does not exist (IE it will not create a double whitespace if one already exists in the prompt)

**Comment by adieyal** [comment] 2023-01-05 18:26
I'm not able to reproduce on my machine. Would you mind testing v2.0.2 to see if it is still happening?

In your extensions/sd-dynamic-prompts folder, type the following commands:

```
git pull -a
git checkout v2.0.2
```

Then restart auto1111

to revert to your current version:

`git checkout main`

Let me know if it is still happening in the new version

**Comment by nordylocks** [comment] 2023-01-05 19:26
I've just updated the main post since the formatting changed the double _ to bold, I'm trying to checkout V2.0.2 but sd-webui doesn't want to launch with 2.0.2 checked out, stuck at installing requirements.

**Comment by adieyal** [comment] 2023-01-05 19:27
could you share a screen shot?

**Comment by adieyal** [comment] 2023-01-05 22:46
I'm not managing to re-create the issue with both `a blue sky:2.9 over a hill` and `a blue sky:2.9over a hill`. Is there anything that you're doing that I'm not?

Btw, what was the issue with it getting stuck on startup?

**Comment by nordylocks** [comment] 2023-01-05 22:56
the Jinja generator seems to generate properly but the (old) generator adds the spaces when I use the prompt `a blue sky:__weight__over a hill`  the output becomes "a blue sky: 2.9 over a hill" where 2.9 is a line from the weight.txt file in wildcards. a space is added both before and after the prompt (running python 3 on linux)

Right now I'm just working on the jinja to work around it (soon as I figure out the syntex for only loading one choices from a wildcards file instead of all of them)

the issue with getting stuck on startup was v2.0.2 requires a different set of requirements then main, specifically it needed torch 1.13.1 which was a 1.8gig download (Cuda version) which when installed as part of the main startup doesn't get listed as being download so instead looks like it's stuck at "installing requirements for Web UI".   main branch was happy with the 1.13.0 I had installed but v2.0.2 wasn't (along with other dependencies it needed)

**Comment by adieyal** [comment] 2023-01-05 23:31
Gotcha, I missed that weights was actually a wildcard. Thanks, I have
something to work with. I'll fix the pytorch dependency issue as well.

**Comment by nordylocks** [comment] 2023-01-05 23:51
I got it working with jinja but created 2 new extensions to assist, thought I would include it here (Sorry it's not a pull request)
`class RandomExtension(Extension):
...
environment.globals["randfloat"] = self.randfloat
...
def randfloat( self, low: int, high: int) -> float:
        return round(random.uniform(low,high),2)'

and
'class WildcardExtension(Extension):
...
environment.globals["wildchoice"] = self.wildchoice

    def wildchoice(self, wildcard_name):
        wm = self.environment.wildcard_manager
        values = random.choice(wm.get_all_values(wildcard_name))
        return values.

**Comment by adieyal** [comment] 2023-01-06 07:25
Good thing I didn't deprecate jinja2. I wasn't sure if anyone was using it.
Thanks for the extensions.

**Comment by adieyal** [comment] 2023-01-07 16:21
Version 2.1.0 should no longer have this issue

**Comment by adieyal** [comment] 2023-01-08 16:54
Closing this issue - please re-open if you spot something else

**Closed by adieyal** 2023-01-08 16:54 UTC
