### ISSUE TITLE
Dynamic prompts, combinatorial repeats itself generation to generation, never randomizes

### ISSUE THREAD

**Issue by bobpuffer1** [adieyal/sd-dynamic-prompts#558] opened 2023-07-14 11:58 UTC
1. Turn on combinatorial
2. Generate 32 images
3. Dynamic prompts chooses your last dynamic prompt, and goes to all of the iterations for that alphabetically
4. as it does that it goes through the iterations of your second to the last dynamic prompt. 
5. And because it goes through those alphabetically anytime you have combinatorial on you start over with each new generation, it produces exactly the same stuff. That's a problem. I'm going to write up an issue.
Desired behavior would be that when combinatorial is on, it's still randomizes its choices image to image, but it goes through all of the choices in accordance with the concept of combinatorial.

**Comment by adieyal** [comment] 2023-07-14 20:50
Not the same, but related to this issue: https://github.com/adieyal/sd-dynamic-prompts/issues/530

**Comment by adieyal** [comment] 2023-07-14 21:10
Actually a duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/328

**Closed by adieyal** 2023-07-14 21:10 UTC
