### ISSUE TITLE
[Bug] Has stopped working completely in 

### ISSUE THREAD

**Issue by roman2838** [adieyal/sd-dynamic-prompts#441] opened 2023-05-23 10:49 UTC
When I have Dynamic prompting enabled in text-2-img I immediately get these error messages
`Error running process: E:\Development\Python\StableDiffusion\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "E:\Development\Python\StableDiffusion\stable-diffusion-webui-ux\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "E:\Development\Python\StableDiffusion\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "E:\Development\Python\StableDiffusion\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'`

And wildcards don't even get evaluated. Also when I hit "Refresh Wildcards" in the wildcards tab, nothing happens (no console logs eiihter). I'm using [anapnoe](https://github.com/anapnoe/stable-diffusion-webui-ux) which is a fork of Automatic111, but I don't think thats the issue here

**Comment by akx** [comment] 2023-05-23 10:51
Duplicate of #439, #438, #436.

Please 

* update your `sd-dynamic-prompts` to the latest d30639722fb812eca3b54bfcb24f19d7783c3bdf
* and make sure the `dynamicprompts` dependencies are up to date with e.g. `python -m pip install -r E:\Development\Python\StableDiffusion\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\requirements.txt`

**Closed** 2023-05-23 11:11 UTC

**Comment by crackfoo** [comment] 2023-05-23 13:34
I continue to get this error even with the package update. I've found that if I have a value other than 0 in the Variation Strength in the Variation seed setting, it throws this error.

**Comment by akx** [comment] 2023-05-23 13:35
@crackfoo Make sure you've stopped and restarted the webui entirely after updating the package. I don't think it's possible for this error to manifest just because you change the variation strength option.

**Comment by akx** [comment] 2023-05-24 07:05
@crackfoo Yeah, moved that to #448.
