### ISSUE TITLE
helpers.py", line 93 - RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'

### ISSUE THREAD

**Issue by sgpascoe** [adieyal/sd-dynamic-prompts#439] opened 2023-05-22 21:56 UTC
```
Error running process: C:\AI\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py4s/it]
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui-ux\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\AI\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "C:\AI\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'
```

**Comment by Chubbly** [comment] 2023-05-22 22:23
I am also getting the same issue. Occurs even when I disable all other extensions. Wildcards are not being parsed correctly, images are generating with the raw text rather than the wildcard value, i.e., generation parameters show  "__nsp/nsp-body/body-fit__ man" instead of "fit man".

**Comment by Danamir** [comment] 2023-05-22 22:34
Related discussion regarding this error in the affected commit : https://github.com/adieyal/sd-dynamic-prompts/commit/3aeda4682b724ebf074692101e205282bc22529c

**Comment by Danamir** [comment] 2023-05-22 22:49
A manual fix is is shown in your log when launching the application : 

```
*** WARNING: Something went wrong when updating to the latest dynamicprompts version. Please install it manually by running the following command:
    <webui path>\venv\Scripts\python.exe -m pip install dynamicprompts==0.25.2
```

(replace `<webui path>` by your installation path)

**Comment by Chubbly** [comment] 2023-05-22 23:25
> A manual fix is is shown in your log when launching the application :
> 
> ```
> *** WARNING: Something went wrong when updating to the latest dynamicprompts version. Please install it manually by running the following command:
>     <webui path>\venv\Scripts\python.exe -m pip install dynamicprompts==0.25.2
> ```
> 
> (replace `<webui path>` by your installation path)

Can confirm that this does work.

One thing to note for others who come across this issue before a fix is issued, on Windows you must provide the full path to your webui python.exe or use the ./ operator if you use a relative path. Otherwise the python that is called is from your PATH, not the venv used by webui. You can tell which version is being updated by checking which file path you see when you run the command. 

This tripped me up and hopefully this help anyone who runs the command but still runs into the issue. Make sure you're updating the right python instance!

**Comment by JPr0k** [comment] 2023-05-23 01:25
same issue here as well

**Comment by awt135** [comment] 2023-05-23 03:25
python -m pip install dynamicprompts==0.25.2 -i  https://pypi.org/simple

**Comment by adieyal** [comment] 2023-05-23 05:30
I'm closing this as a duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/438

**Closed by adieyal** 2023-05-23 05:30 UTC
