### ISSUE TITLE
RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'

### ISSUE THREAD

**Issue by whmc76** [adieyal/sd-dynamic-prompts#453] opened 2023-05-25 03:04 UTC
Error running process: E:\novelai-webui-aki-v3\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "E:\novelai-webui-aki-v3\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "E:\novelai-webui-aki-v3\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "E:\novelai-webui-aki-v3\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'

Dynamic Prompts is not installed correctly. Please reinstall the dynamic prompts library by running the following command: E:\novelai-webui-aki-v3\py310\python.exe -m pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.25.2'

I have tried uninstalling and reinstalling 2 times and still have the same problem

dynamic prompt
b88e1159 (Wed May 24 08:05:38 2023)
and latest webui version

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by akx** [comment] 2023-05-25 06:14
Did you run that command?

Duplicate of #441, anyway.

**Closed by akx** 2023-05-25 06:14 UTC
