### ISSUE TITLE
[Bug] Unable to use dynamic prompts after updating the new version

### ISSUE THREAD

**Issue by richadlee** [adieyal/sd-dynamic-prompts#443] opened 2023-05-23 14:58 UTC
The following prompts were available before the update, but an error was reported after the update

Prompts:
{<lora:girl_v8-000028:{0.5|0.6}>|<lora:girl_v4:{0.5|0.6}>|<lora:girl_v1-000024:{0.5|0.6}>|<lora:girl_v5:{0.5|0.6}>|<lora:girl_v6-000024:{0.5|0.6}>|<lora:girl_v6:{0.5|0.6}>|<lora:girl_v2-000016:{0.5|0.6}>}

Error:
Create LRU cache (max_size=16) for preprocessor results.
                                  Error running process: D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\00_AI\stable-diffusion-webui_23-02-17\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'

Error running process: D:\00_AI\stable-diffusion-webui_23-02-17\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
Traceback (most recent call last):
  File "D:\00_AI\stable-diffusion-webui_23-02-17\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py", line 54, in process
    composable_lora.load_prompt_loras(prompt)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 19, in load_prompt_loras
    multiplier = float(params.items[1]) if len(params.items) > 1 else 1.0
ValueError: could not convert string to float: '{0.5|0.6}'

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C65F0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C5F60>, <modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C6410>, <modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C7610>, <modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C6350>, <modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C75E0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001C4665C72B0>]: ValueError
Traceback (most recent call last):
  File "D:\00_AI\stable-diffusion-webui_23-02-17\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions-builtin\Lora\extra_networks_lora.py", line 21, in activate
    multipliers.append(float(params.items[1]) if len(params.items) > 1 else 1.0)
ValueError: could not convert string to float: '{0.5|0.6}'

**Comment by Appolonius001** [comment] 2023-05-23 15:58
same here

**Comment by Pokis** [comment] 2023-05-23 16:26
seems duplicate: https://github.com/adieyal/sd-dynamic-prompts/issues/441 but still cannot make it work even after updating stable diffusion, extensions and even my local python to latest versions.

**Comment by medledan** [comment] 2023-05-23 17:40
My issue with this extension is that Hires. fix no longer works when the extension is enabled. I click the X and no additional hire.fix options appear. I turn the extension off again and Hires. fix works again.

**Comment by wietelmann** [comment] 2023-05-23 18:22
same here, and sadly nether #441 nor #438 nor reinstalling fixed it - uff :(
- Windows 10

**Comment by monstari** [comment] 2023-05-23 19:27
Same here, I am using collab 

Prompt: {pink|white},
Output: {pink|white}, doesn't pick.

Dynamic Prompts is also enabled.

**Comment by GeneralAwareness** [comment] 2023-05-24 01:18
Add me to this list after just updating.  I swear, this entire SD stuff is the only project I am afraid to ever update to because the devs don't test their shit then make sure it works to copy it over on github to make it the new head.  I had one dev tell me they never test.  Since then I just sort of expect it so update rarely.

**Comment by wzgrx** [comment] 2023-05-24 01:35
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "G:\Soft\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\Soft\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Soft\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "G:\Soft\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 12, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
  File "G:\Soft\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\__init__.py", line 7, in <module>
    from dynamicprompts.generators.jinjagenerator import JinjaGenerator
  File "G:\Soft\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\jinjagenerator.py", line 14, in <module>
    from dynamicprompts.jinja_extensions import DYNAMICPROMPTS_FUNCTIONS, PromptExtension
  File "G:\Soft\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\jinja_extensions.py", line 8, in <module>
    from jinja2 import Environment, pass_environment
ImportError: cannot import name 'pass_environment' from 'jinja2' (G:\Soft\stable-diffusion-webui\venv\lib\site-packages\jinja2\__init__.py)

**Comment by adieyal** [comment] 2023-05-24 05:35
This issue is a duplicate of #441 - if you are getting an error relating to unexpected argument seeds, it means that your dynamicprompts dependency didn't update automatically as it should. In the terminal you will see a command that you should run to install it manually. Make sure you are using the correct python installation - the command in the terminal has a the path to make sure that you are using the correct one.

**Closed by adieyal** 2023-05-24 05:35 UTC
