### ISSUE TITLE
I get an error when I check ”Dynamic Prompts enabled”

### ISSUE THREAD

**Issue by twinkle555** [adieyal/sd-dynamic-prompts#445] opened 2023-05-24 01:54 UTC
I get the following error And dynamic prompt does not work. I applied the latest update and this is what I get.

Error running process: F:\StableDiffusion20230313\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "F:\StableDiffusion20230313\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "F:\StableDiffusion20230313\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "F:\StableDiffusion20230313\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: BatchedCombinatorialPromptGenerator.generate() got an unexpected keyword argument 'seeds'

**Comment by adieyal** [comment] 2023-05-24 05:29
Closed as a duplicate of #441

**Closed by adieyal** 2023-05-24 05:29 UTC
