### ISSUE TITLE
Multiples not working?

### ISSUE THREAD

**Issue by Jonseed** [adieyal/sd-dynamic-prompts#268] opened 2023-02-21 21:07 UTC
**Describe the bug**
I have a prompt with the format ``{2$$__wildcardfile__}`` but it is not selecting two elements from the file, but just one. I also tried ``{2$$ and $$__wildcardfile__}`` and still only get one element. It seems adding two or more options is not working? I am on commit 9a38f02e

**Are you using a local install or a colab?**
local

**Expected behaviour**
Puts multiple elements into the prompt from a wildcard file.

**Comment by adieyal** [comment] 2023-02-23 12:17
That functionality is not working at the moment, as a work around you will need to list the wildcard multiple times, i.e. `{__wildcardfile__|__wildcardfile__|__wildcardfile__}`

**Comment by Jonseed** [comment] 2023-02-28 21:20
But that just picks one from the list, since it is the same list three times with the "or" | between them. I guess to get multiples I would just list the wildcardfile alone, like `__wildcardfile__ __wildcardfile__` ?

**Comment by adieyal** [comment] 2023-03-01 05:45
sorry,  typo `{3$$__wildcardfile__|__wildcardfile__|__wildcardfile__}`, but yeah, effectively the same as `__wildcardfile__ __wildcardfile__ __wildcardfile__` if you're not planning on adding additional values to your variant. Our next release will include a big change to what you can do with prompts, this feature will be fixed after that.

**Comment by adieyal** [comment] 2023-03-25 12:11
Closing this issue since it's a duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/307

**Closed by adieyal** 2023-03-25 12:11 UTC
Labels: bug
