### ISSUE TITLE
X/Y Plot?

### ISSUE THREAD

**Issue by Adil3tr** [adieyal/sd-dynamic-prompts#110] opened 2022-12-11 17:00 UTC
`X/Y Plot - setting Dynamic Prompts to [combinatorial mode](https://github.com/adieyal/sd-dynamic-prompts#combinatorial-generation) while using X/Y Plot, lets you exhaustively test prompt and paramter variations simultaneously.`

What does this mean? I would like to be able to make an X/Y plot where one axis is every single entry, or a random selection, from a wildcard but I cannot comprehend this paragraph. 

I tried making a prompt "I {love|hate}" and then making an X/Y plot that's just an X axis with steps "10,20" and turned on combinatorial mode set to a max of 10. This failed completely. It created one 2x1 grid, and 8 extra images not put in any grid, all with the prompt "I hate." 

Is it possible to use this with the X/Y grid script or not?

**Comment by adieyal** [comment] 2022-12-12 13:39
Try this example:

1. Select combinatorial mode
![Screenshot from 2022-12-12 15-34-39](https://user-images.githubusercontent.com/420786/207057880-63ec24f2-4495-4815-a67e-95be257f565c.png)
2. Set the prompt to `I love {red|green} {circles|squares}`
3. Set num_batches to four (i.e. colours x shapes = 4)
![Screenshot from 2022-12-12 15-33-46](https://user-images.githubusercontent.com/420786/207057707-6e41bbf5-f44f-4fdf-8beb-94ed72b4849f.png)
4. Set the steps of XY plot to be 10,20
![Screenshot from 2022-12-12 15-33-33](https://user-images.githubusercontent.com/420786/207057713-d9177668-0a4f-4a30-ab59-05490af9dba8.png)
5. Generate
![Screenshot from 2022-12-12 15-33-22](https://user-images.githubusercontent.com/420786/207057716-ebcd6b15-0e1b-47ca-9f75-7f08329174bf.png)

You'll notice 3 grids corresponding with steps=10, steps=20 and steps=30
In each grid, you will see 4 images, corresponding to:
1. I love red circles
2. I love red squares
3. I love green circles
4. I love green squares

In your case, you would have two grids (i.e. steps=10 and steps=20). Each grid will have two images, I love and I hate.

Not sure why you are seeing extra images.

**Comment by Adil3tr** [comment] 2022-12-12 18:04
[https://media.discordapp.net/attachments/993577921702789220/1051922318743576696/image.png?width=719&height=266](url)

It did not create one grid with 4 images in each square. I've never been able to make the XYplot script do that.

**Comment by adieyal** [comment] 2022-12-15 09:04
what was your prompt in this example?

**Comment by Adil3tr** [comment] 2022-12-15 23:51
> what was your prompt in this example?

Exactly the same as yours, just with apples and bannanas instead of circles and squares.

**Comment by adieyal** [comment] 2023-03-11 09:10
Closing this issue as I can't reproduce it

**Closed by adieyal** 2023-03-11 09:10 UTC
Labels: question
