### ISSUE TITLE
Magic prompts broken?

### ISSUE THREAD

**Issue by space-nuko** [adieyal/sd-dynamic-prompts#116] opened 2022-12-15 05:10 UTC
**Describe the bug**
Recently when I activate the magic prompt feature I can't generate images, instead I get this error

```
Traceback (most recent call last):
  File "D:\build\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "D:\build\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "D:\build\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = process_images(p)
  File "D:\build\stable-diffusion-webui\modules\processing.py", line 465, in process_images
    res = process_images_inner(p)
  File "D:\build\stable-diffusion-webui\modules\processing.py", line 568, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\build\stable-diffusion-webui\modules\processing.py", line 704, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x, self.firstphase_width, self.firstphase_height))
  File "D:\build\stable-diffusion-webui\modules\sd_samplers.py", line 507, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\build\stable-diffusion-webui\modules\sd_samplers.py", line 422, in launch_sampling
    return func()
  File "D:\build\stable-diffusion-webui\modules\sd_samplers.py", line 507, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\build\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\build\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\build\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\build\stable-diffusion-webui\modules\sd_samplers.py", line 296, in forward
    uncond = prompt_parser.reconstruct_cond_batch(uncond, self.step)
  File "D:\build\stable-diffusion-webui\modules\prompt_parser.py", line 221, in reconstruct_cond_batch
    res[i] = cond_schedule[target_index].cond
RuntimeError: The expanded size of the tensor (77) must match the existing size (154) at non-singleton dimension 0.  Target sizes: [77, 768].  Tensor sizes: [154, 768]
```

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Activate magic prompts
2. Generate an image

Also mention which checkboxes have been set.

**Expected behaviour**
Magic prompts should work

**Additional context**
N/A

**Comment by adieyal** [comment] 2022-12-15 08:44
Looks like this broke after a recent change to auto1111, looking into it

**Comment by adieyal** [comment] 2022-12-15 08:59
can you consistently reproduce it? It broke for me once, but now it seems to work.

**Comment by space-nuko** [comment] 2022-12-15 23:06
Still doesnt work for me, is there perhaps a cached model I should delete or similar?

**Comment by adieyal** [comment] 2022-12-16 08:29
On my machine the model can found at $HOME/.cache/huggingface/hub/models--Gustavosta--MagicPrompt-Stable-Diffusion

**Comment by adieyal** [comment] 2022-12-16 08:54
Does it happen consistently? It happened once for me, and not again, not sure why

**Comment by space-nuko** [comment] 2022-12-17 06:47
I cleared the cache folder you mentioned and it worked, thanks. I was trying to just search "magic prompts" and I didn't find the model you mentioned at the same path, so I just deleted the entire `huggingface` folder

Might be helpful to add a note for anyone who encounters the same error

**Comment by adieyal** [comment] 2022-12-17 16:00
Thanks for the feedback. I'm glad that you're back up and running. I'll add
a note.

**Comment by space-nuko** [comment] 2022-12-18 04:08
Nevermind, I actually found that after running magic prompts multiple times in a row it gives the same error. It does work at least once before that happens though

**Comment by pawprint** [comment] 2022-12-19 20:37
Getting this as well - not every time but frequently. I thought it was every other time for a while but it's more than that.

**Comment by pawprint** [comment] 2022-12-20 18:28
Just a followup - I can confirm leaving the max prompt length to 80 or lower it works every time.

**Comment by adieyal** [comment] 2022-12-22 02:54
I'm able to reproduce the issue when setting max_prompt length to 154. From your error message, it seems like that is that value that you are using. Could you please confirm whether you still get the error with different values?

**Comment by adieyal** [comment] 2022-12-31 14:43
I'm closing this issue because I can't reproduce it - please re-open it if it happens again

**Closed by adieyal** 2022-12-31 14:43 UTC
