### ISSUE TITLE
Runing dymamic prompts/magic prompts with a few existing prompts cause no prompts to generate

### ISSUE THREAD

**Issue by mailani19** [adieyal/sd-dynamic-prompts#301] opened 2023-03-08 03:55 UTC
**Describe the bug**
As said in the title, having 4-5 prompts causes no prompts to generate even with
 magic prompt length turned up to 200 or 300 characters. 
**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
turn on dynamic and magic prompts, enter in a couple of your own prompts and run it.  

furry art, uploaded on e621:1.4, (anthro furry:1.5),  ((loona:1.5)), 

as an example of the prompts used. 

Also mention which checkboxes have been set.
dynamic prompts, magic prompts
**Are you using a local install or a colab?**
np
If a colab, which one?
N/A
**Expected behaviour**
Expected it to add random prompts up to the set character limit selected on the slider
**Additional context**
it does literally nothing unless i only have like 1-2 very short prompts, no LoRAs, no anything else. 
It also gives no errors. 
I also tried combinatoral generation 
max generation 0
tried batches on 1,2 and 3
in all cases it did 1 batch without any random prompts added and then stopped. 
No errors.

**Comment by adieyal** [comment] 2023-03-24 20:15
Do you see any errors in your console? I can't reproduce this with your prompt

**Comment by akx** [comment] 2023-04-13 18:07
Closing 🧹

**Closed by akx** 2023-04-13 18:07 UTC
Labels: bug
