### ISSUE TITLE
WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item

### ISSUE THREAD

**Issue by 925-Studio** [adieyal/sd-dynamic-prompts#671] opened 2023-11-10 17:36 UTC
After updated to the latest version, my console shows this error message: `WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item` for all my `.yaml` wildcards.

Those `.yaml` wildcards still work though.

I don't have `.txt` or `.json` wildcard, only `.yaml`, any ideas? Thanks in advance.

My `.yaml` wildcard example:
```
color:
  css:
    - alice_blue
    - antique_white
    - aqua
    - aquamarine
    - azure
    - beige
    - bisque
    - black
    - blanched_almond
    - blue
    - blue_violet
    - brown
    - burlywood
    - cadet_blue
    ...
```

**Comment by DavideAlidosi** [comment] 2023-11-10 17:43
I have the same issue on all of my wildcard .yalm and .txt

**Comment by DavideAlidosi** [comment] 2023-11-10 17:54
I've make some more test, the issue is related only on .yalm one, it's easly repicable by using this CivitAI resource:
[https://civitai.com/models/138970/billions-of-wildcards-all-in-one](https://civitai.com/models/138970/billions-of-wildcards-all-in-one)

**Comment by StanleyPain** [comment] 2023-11-10 18:57
I've been seeing this error pop up over the last couple of days. Also having strange things happening where wildcards aren't parsing at all.

**Comment by Dragoy** [comment] 2023-11-10 22:43
I join the problem, I thought I was the only one.

**Comment by adieyal** [comment] 2023-11-10 23:18
Can someone please test [this file](https://github.com/adieyal/sd-dynamic-prompts/raw/main/collections/publicprompts.yaml) to see if you get the same message?

**Comment by StanleyPain** [comment] 2023-11-11 00:17
No dice with that file.

**Comment by 925-Studio** [comment] 2023-11-11 09:13
> Can someone please test [this file](https://github.com/adieyal/sd-dynamic-prompts/raw/main/collections/publicprompts.yaml) to see if you get the same message?

Still has same problem. I deleted all my wildcard files and just keep the one from you and as soon as I switched to the Wildcards Manager the error showed up. Here is a part of the error message:
```
Running on local URL:  http://127.0.0.1:6006

To create a public link, set `share=True` in `launch()`.
Startup time: 15.9s (prepare environment: 3.3s, import torch: 3.6s, import gradio: 0.9s, setup paths: 1.4s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 3.9s, create ui: 1.6s, gradio launch: 0.3s).
Applying attention optimization: xformers... done.
Model loaded in 6.7s (load weights from disk: 1.0s, create model: 1.4s, apply weights to model: 2.9s, calculate empty prompt: 1.1s).
WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item: # Usage: <object>, __public-prompts/styles/3d-render(color_scheme=soft pastel)__
# Homepage: https://publicprompts.art/

__public-prompts/lighting/soft-smooth__,
${color_scheme:soft pastel} colors,
3d, blender render,
polycount, modular constructivism,
physically based rendering,
square image

WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item: soft smooth lighting
WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item: vibrant studio lighting
WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item: diffused lighting
WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item: # Usage: __public-prompts/needle-felted(figure=frog)__
# Homepage: https://publicprompts.art/needle-felted-objects/
# Suggested settings:
# CFG scale: 13
# Sampler DDIM
# Steps: 25

Tiny cute 3D felt fiber toy ${figure:frog}, made from Felt fibers, a 3D render, trending on cgsociety, rendered in maya, rendered in cinema4d, made of yarn, square image

WARNING:dynamicprompts.wildcards.collection.structured:Unsupported list item: # Usage: __public-prompts/silhouetted-backgrounds(natural-feature=mountains,object=big rocket)__
# Homepage: https://publicprompts.art/silhouette-wallpapers/
# Suggested settings:
# CFG scale: 13
# Sampler DDIM
# Steps: 25
# Resolution: 704x384
...
```

**Comment by DavideAlidosi** [comment] 2023-11-11 10:13
I have roll back to a release of a week ago, and not have any issue at all, for sure this is a regression.

**Comment by akx** [comment] 2023-11-11 10:53
This is fixed in https://github.com/adieyal/dynamicprompts/pull/105 already - the warning is harmless but annoying.

**Comment by akx** [comment] 2023-11-11 11:03
Fixed in `main`.

**Closed by akx** 2023-11-11 11:03 UTC
Labels: bug

**Comment by 925-Studio** [comment] 2023-11-11 12:33
> Fixed in `main`.

Now I get `ERROR: No matching distribution found for dynamicprompts~=0.30.3` error. I'm using Python 3.10.6 and I've tried to use `pip install dynamicprompts==0.30.3` and the highest version I can reach for now is '0.30.2'. How can I fix this? Thanks.

```
*** Error running install.py for extension /root/sd-webui/extensions/sd-dynamic_prompts.
*** Command: "/root/miniconda3/envs/my-env/bin/python" "/root/sd-webui/extensions/sd-dynamic_prompts/install.py"
*** Error code: 1
*** stdout: Looking in indexes: http://mirrors.aliyun.com/pypi/simple
*** sd-dynamic-prompts installer: running /root/miniconda3/envs/my-env/bin/python -m pip install 'dynamicprompts[attentiongrabber,magicprompt]~=0.30.3'
*** 
*** stderr: ERROR: Ignored the following yanked versions: 0.30.0
*** ERROR: Could not find a version that satisfies the requirement dynamicprompts~=0.30.3 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.20.0, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.1, 0.30.2rc0, 0.30.2)
*** ERROR: No matching distribution found for dynamicprompts~=0.30.3
*** Traceback (most recent call last):
***   File "/root/sd-webui/extensions/sd-dynamic_prompts/install.py", line 14, in <module>
***     install_requirements(force=("-f" in sys.argv))
***   File "/root/sd-webui/extensions/sd-dynamic_prompts/sd_dynamic_prompts/version_tools.py", line 144, in install_requirements
***     subprocess.check_call(command)
***   File "/root/miniconda3/envs/my-env/lib/python3.10/subprocess.py", line 369, in check_call
***     raise CalledProcessError(retcode, cmd)
*** subprocess.CalledProcessError: Command '['/root/miniconda3/envs/my-env/bin/python', '-m', 'pip', 'install', 'dynamicprompts[attentiongrabber,magicprompt]~=0.30.3']' returned non-zero exit status 1.
```

**Comment by adieyal** [comment] 2023-11-11 13:37
not sure how the distribution works, but perhaps it takes a little time. I see the latest version here: https://pypi.org/project/dynamicprompts/

**Comment by 925-Studio** [comment] 2023-11-11 16:11
> not sure how the distribution works, but perhaps it takes a little time. I see the latest version here: https://pypi.org/project/dynamicprompts/

It's working and without the error message. Thank you and @akx very much.

**Comment by Hunt3rseeker** [comment] 2024-05-16 15:52
The bug has risen again, gotten it all day and it came out of nowhere. I just found the thread and I'll try the fix and cross my fingers.
