### ISSUE TITLE
Multiple dynamic prompts completely broken?

### ISSUE THREAD

**Issue by Velour-Fog** [adieyal/sd-dynamic-prompts#237] opened 2023-02-04 01:33 UTC
**Describe the bug**
having more than 1 dynamic prompt that specifies more than 1 prompt be chosen breaks formatting.

What I mean by this is a prompt: "{2$$ 1| 2| 3}" by itself works and produces: "2, 3"
But a prompt: "{2$$ 1| 2| 3} {2$$ 1| 2| 3}" produces: "2 1| 2| 3} {2 3"

Surprised I didn't see any report on this, seems like some core functionality broke in a recent update.

**Comment by akx** [comment] 2023-02-04 11:08
This seems to be a duplicate of #223.

The current version of the `dynamicprompts` library seems to be parsing that correctly, so please make sure you've updated everything – you can manually try to `pip install -U dynamicprompts` too.

**Comment by Velour-Fog** [comment] 2023-02-04 22:57
I tried deleteing the extension, and just doing a git clone instead of installing via automatic1111, and same issue.
I tried pip install -U dynamicprompts, which seemed like it did something in the console, but still same issue.
This should probably be a top prio to fix, as any new users will have this issue, and may not even notice/understand why the output is scrambled. They may just think they are formatting the syntax wrong.
I suppose ill try to roll back to a previous version for now.

**Comment by Velour-Fog** [comment] 2023-02-04 23:08
Heads up to anyone encountering this issue: "git checkout 7bb4029" seems to be working until this is resolved. This is the 2.5.0 version

**Comment by Ame-Gura** [comment] 2023-02-05 10:39
I had the same issue, but downgrading to version 2.5.0 resolved it.

**Comment by akx** [comment] 2023-02-06 18:16
Ah, I guess there hasn't been a new PyPI release of `dynamicprompts` (ping @adieyal) with the bugfixes...

**Comment by adieyal** [comment] 2023-02-06 20:11
@Ame-Gura @Velour-Fog  - could you please update and let us know if it's working?

**Comment by Velour-Fog** [comment] 2023-02-06 21:17
It appears to be fixed! thanks.

**Closed** 2023-02-06 21:33 UTC
Labels: bug
