### ISSUE TITLE
error after update to v1.4.0

### ISSUE THREAD

**Issue by hunssandwich** [adieyal/sd-dynamic-prompts#554] opened 2023-07-10 14:19 UTC
Traceback (most recent call last):
      File "C:\Users\junhe\Desktop\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "C:\Users\junhe\Desktop\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 478, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "C:\Users\junhe\Desktop\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "C:\Users\junhe\Desktop\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
        prompts.append(next(iter(gen)))
    StopIteration

**Comment by hunssandwich** [comment] 2023-07-11 01:09
> Are you sure you're quoting the correct version number?
> 
> The latest version of the extension is 2.12.6 and the dynamic prompts library is currently at 0.27.1

I meant web UI version v1.4.0
just had an update yesterday

**Comment by akx** [comment] 2023-07-11 07:05
This looks like a duplicate of #542 and #513.

**Closed** 2023-07-17 09:54 UTC
