### ISSUE TITLE
Feature Request: Randomize lora weights

### ISSUE THREAD

**Issue by nialv7** [adieyal/sd-dynamic-prompts#434] opened 2023-05-19 19:20 UTC
like attention grabber that randomizes weights of certain words, it could also be useful to randomize weights for Loras

**Comment by Appolonius001** [comment] 2023-05-23 16:04
to randomize weights i use something like this <lora:ArtNouveauAI:{1|.9|.8|.7}> and so on. also i made a wild card with number ranges so i can use __weight__ and it places a random weight anywhere i want

**Comment by akx** [comment] 2023-05-26 07:36
Duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/236 for all practical purposes, keep an eye on that one :)

**Closed by akx** 2023-05-26 07:36 UTC
Labels: enhancement
