### ISSUE TITLE
Selecting multiple prompts from a wildcard only picks 1

### ISSUE THREAD

**Issue by Velour-Fog** [adieyal/sd-dynamic-prompts#246] opened 2023-02-06 23:26 UTC
`{2-5$$ 1| 2| 3| 4| 5}` works fine and produces: "1, 3, 3, 4"

`{2-5$$ __enhance-photo__}` doesn't work and only produces: "rim lighting"

**Comment by adieyal** [comment] 2023-02-07 06:32
That's a bug, but I'm not planning on supporting that syntax in the next version as the code to enable it while at the same time preventing duplicates is tricky with the new structure. It will likely be re-introduced later on. Let's keep this ticket open, but I won't look at it until after the new release.

**Comment by bitshifter52** [comment] 2023-02-11 20:56
I was going to create a new issue, but this appears to be related. The following **{18|19|20|21|22}** doesn't work anymore. What I'm seeing is the entire **{18|19|20|21|22}** and not the individual numbers which were working before I did the latest update to sd-dynamic-prompts. It was working before the update.

The __rscollection/Nature/flower__ wildcard syntax no longer works. 

I'm seeing these errors after the update for both the "__wildcard-list__" and the "{val1 | val2| val3}" prompts:

Error running process: /home/{user}/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/home/{user}/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/home/{user}/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 408, in process
    generator = generator_builder.create_generator()
  File "/home/{user}/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/generator_builder.py", line 149, in create_generator
    generator = self.create_basic_generator()
  File "/home/{user}/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/generator_builder.py", line 177, in create_basic_generator
    prompt_generator = CombinatorialPromptGenerator(
TypeError: CombinatorialPromptGenerator.__init__() got an unexpected keyword argument 'parser_config'

This has been a very wonderful feature and I hope it can be fixed soon. Thanks

**Comment by adieyal** [comment] 2023-02-11 21:22
Did you restart the webui when you updated?

Could you please run this from your terminal and let me know if it fixes it: 
`venv/bin/python -m pip install dynamicprompts==0.7.0`

**Comment by space-nuko** [comment] 2023-02-13 12:04
Same error, even after reinstalling with pip, used combinatorial generation

**Comment by adieyal** [comment] 2023-02-13 12:14
What is the output of 
```
python -c "import dynamicprompts; print(dynamicprompts.__version__)"
```

**Comment by adieyal** [comment] 2023-02-13 12:38
I think this is a duplicate of #255  - please update your extension and let me know if that update fixes it.

**Comment by space-nuko** [comment] 2023-02-13 14:21
`0.7.0`

**Comment by adieyal** [comment] 2023-02-13 14:27
should be 0.7.1 - did you update the extension in the last hour?

**Comment by space-nuko** [comment] 2023-02-14 08:29
I updated now and it should be fine

**Closed** 2023-02-15 06:18 UTC
Labels: bug
