### ISSUE TITLE
since the last commit : getting error on RandomPromptGenerator.generate() 

### ISSUE THREAD

**Issue by RannaAI** [adieyal/sd-dynamic-prompts#436] opened 2023-05-22 11:59 UTC
a fresh install of the whole system still give me the error:

```
Error running process: /content/sdw/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/content/sdw/modules/scripts.py", line 418, in process
    script.process(p, *script_args)
  File "/content/sdw/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "/content/sdw/extensions/sd-dynamic-prompts/sd_dynamic_prompts/helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'
```

**Comment by RannaAI** [comment] 2023-05-22 12:32
i had to use this and it got working again
`!pip install  --upgrade dynamicprompts`

**Comment by akx** [comment] 2023-05-22 12:34
That means it wasn't exactly a fresh install, then 😄 

Anyway, glad you got it to work, closing this.

**Closed by akx** 2023-05-22 12:34 UTC

**Comment by RannaAI** [comment] 2023-05-22 13:09
I don't know if colab keeps a machine residue when you destroy/delete one and create a new one, maybe it's colab's issue. 
but the only way to get this working was by installing the update manually like what I stated.

**Comment by RannaAI** [comment] 2023-05-22 20:26
> That means it wasn't exactly a fresh install, then 😄
> 
> Anyway, glad you got it to work, closing this.

I tried a fresh install just to make sure, and it didn't work, I still have to install it manually, maybe there is an issue about the required version on the install script., please reopen until it get fixed

**Comment by adieyal** [comment] 2023-05-23 05:32
Can you retry now? I fixed a compatibility issue with the install script that may have been affecting colabs. Also, worth noting that this is a duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/438
