### ISSUE TITLE
Dynamic Prompts is not installed correctly. Please reinstall the dynamic prompts library by running the following command: xxxxxxx\python.exe -m pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.25.2'

### ISSUE THREAD

**Issue by shingsss** [adieyal/sd-dynamic-prompts#456] opened 2023-05-26 02:36 UTC

**Comment by akx** [comment] 2023-05-26 07:27
Please do what the error message says. Duplicate of #441.

**Closed by akx** 2023-05-26 07:27 UTC
