### ISSUE TITLE
Install.py Error on Startup

### ISSUE THREAD

**Issue by nxn46** [adieyal/sd-dynamic-prompts#218] opened 2023-01-27 01:07 UTC
A copy and paste of my comment on the recent commit changing Install.py (97bea0f). I can't properly install sd-dynamic-prompts, the repository is cloned properly by A1111 and through Git bash terminal, but the install file to download dependencies fails.

The end result is there's no dynamic prompts tab under either txt2img or img2img and nothing in the extension functions.

------

Tried updating from a previous version from two weeks ago and got this error.
Deleted the extension completely and reinstalled from A1111's menu, same error.

```
Error running install.py for extension C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts.
Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py", line 4, in <module>
    from dynamicprompts.utils import is_empty_line
ModuleNotFoundError: No module named 'dynamicprompts.utils'


Closing server running on port: 7860
Restarting UI...
Error calling: C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py/ui
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 120, in ui
    WILDCARD_DIR=wildcard_manager.path,
AttributeError: 'WildcardManager' object has no attribute 'path'

Error calling: C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py/ui
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 120, in ui
    WILDCARD_DIR=wildcard_manager.path,
AttributeError: 'WildcardManager' object has no attribute 'path'

Error executing callback ui_tabs_callback for C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\ui\wildcards_tab.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 106, in ui_tabs_callback
    res += c.callback() or []
  File "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\ui\wildcards_tab.py", line 63, in on_ui_tabs
    <li>4. Optional - add your own wildcards files to the {wildcard_manager.path} folder</li>
AttributeError: 'WildcardManager' object has no attribute 'path'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

This occurs even after running the "python -m pip install dynamicprompts" suggested in the readme:

```
(venv) C:\AI\stable-diffusion-webui>python -m pip install dynamicprompts
Requirement already satisfied: dynamicprompts in c:\ai\stable-diffusion-webui\venv\lib\site-packages (0.3.0)
Collecting requests<3.0.0,>=2.28.1
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.64.1 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts) (4.64.1)
Requirement already satisfied: jinja2<4.0.0,>=3.1.2 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts) (3.1.2)
Requirement already satisfied: pyparsing<4.0.0,>=3.0.9 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts) (3.0.9)
Requirement already satisfied: MarkupSafe>=2.0 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from jinja2<4.0.0,>=3.1.2->dynamicprompts) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (2022.9.24)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (1.26.12)
Requirement already satisfied: colorama in c:\ai\stable-diffusion-webui\venv\lib\site-packages (from tqdm<5.0.0,>=4.64.1->dynamicprompts) (0.4.5)
Installing collected packages: requests
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
clean-fid 0.1.29 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.
Successfully installed requests-2.28.2

[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) C:\AI\stable-diffusion-webui>webui-user.bat

(venv) C:\AI\stable-diffusion-webui>git pull https://github.com/AUTOMATIC1111/stable-diffusion-webui
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch            HEAD       -> FETCH_HEAD
Already up to date.
venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 7a14c8ab45da8a681792a6331d48a88dd684a0a9
Installing requirements for Web UI
Error running install.py for extension extensions\sd-dynamic-prompts.
Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd-dynamic-prompts\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py", line 4, in <module>
    from dynamicprompts.utils import is_empty_line
ModuleNotFoundError: No module named 'dynamicprompts.utils'
```

**Comment by Yurucomf** [comment] 2023-01-27 03:14
I'm having the same issue. Was working fine yesterday.

```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 10, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
ModuleNotFoundError: No module named 'dynamicprompts'
```

**Comment by adieyal** [comment] 2023-01-27 05:15
Could you please try the latest version of DP - I just push a change that should fix the problem.

**Comment by adieyal** [comment] 2023-01-27 05:19
Dupe of #209

**Closed by adieyal** 2023-01-27 05:19 UTC

**Comment by Yurucomf** [comment] 2023-01-28 00:37
Works now :]
