### ISSUE TITLE
TypeError: Script.process() missing 18 required positional arguments

### ISSUE THREAD

**Issue by chrisnorth90** [adieyal/sd-dynamic-prompts#584] opened 2023-08-02 18:28 UTC
Whenever I click "Generate", this error pops up in the console:

<img width="639" alt="image" src="https://github.com/adieyal/sd-dynamic-prompts/assets/75340148/769d54a1-74d1-48af-b627-81eb66b60ccc">

This error pops up whether I have Dynamic Prompts enabled or disabled. As a result of this error, it seems like DP isn't doing anything, though the panel does show up correctly in webui.

I'm on windows 10. DP is version 2.1.4. Library is 0.29.0

Thanks for any help!

**Comment by adieyal** [comment] 2023-08-02 20:18
That's really strange. Did this just start happening? What version of auto1111 are you using?

**Comment by chrisnorth90** [comment] 2023-08-02 20:27
v1.5.1.

I only installed DP yesterday, so I can't say if it was happening before.

**Comment by pmcculler** [comment] 2023-08-03 18:55
This usually happens to me when the front end and back end are out of sync. Shutting down all tabs and the backend then restarting them clears it up for me, but your mileage may vary.

**Comment by adieyal** [comment] 2023-08-13 19:38
I'm closing this for now as I can't reproduce. What @pmcculler says makes sense. If you get that error, then something is very wrong with Auto1111. Re-open if this recurs and you think it's related to DP.

**Closed by adieyal** 2023-08-13 19:38 UTC
